services:
  - type: web
    name: back2life-audio-processing
    runtime: docker
    region: oregon
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000